# Path to oh-my-zsh
export ZSH=$HOME/.oh-my-zsh

# Zsh_theme
ZSH_THEME="das"

plugins=(git)

## User configuration
# Alias
alias ls="ls --color=auto"            #Add some colours
alias diff="colordiff"                #Same here
alias rzc="source ~/.zshrc"           #Reload Zsh configuration file (The one you're reading just now)
alias dhcpcd="sudo dhcpcd"
alias mount="sudo mount"
alias umount="sudo umount"
alias pg="sudo ping google.fr -c 15"  #Did I'm at least connected ?
alias ip="DasIP"                      #Shorter than DasIP

# Alias (Mac specific)
alias ring="afplay /System/Library/Sounds/Glass.aiff"

# DaScripts
alias DasIP="echo '$(curl -s http://ipecho.net/plain)'"           #Display IP
alias DasMount="sudo mount /dev/sdc1 /mnt/usb && cd /mnt/usb"     #Mount to /mnt/usb and goto
alias DasPing="sudo ping daspat.fr -c 15"                         #DASPAT is still on ?
alias DasUmount="sudo umount /mnt/usb/"
alias DasV="uname -a"                                             #What the thing I'm on ?


## Environment variables
# Browser/Editor
export BROWSER="firefox"
export EDITOR="vim"

# Locale
export LANG="en_GB"
export LC_NUMERIC="fr_FR.utf8"
export LC_PAPER="fr_FR.utf8"
export LC_ADDRESS="fr_FR.utf8"
export LC_TELEPHONE="fr_FR.utf8"
export LC_MEASUREMENT="fr_FR.utf8"
export LC_TIME="fr_FR.utf8"

source $ZSH/oh-my-zsh.sh
