# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="das"
#ZSH_THEME="geoffgarside"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

## User configuration

# AutoRehash
zstyle ':completion:*' rehash true

# Alias
alias dhcpcd='sudo dhcpcd'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias mount='sudo mount'
alias pacman='sudo pacman'
alias p='pwd'
alias pg='sudo ping google.fr -c 15'
alias segv='LD_PRELOAD=~/Prog/my_malloc.so'
alias tree='tree -C'
alias umount='sudo umount'
alias vcat='vimcat'
alias wifi-menu='sudo wifi-menu'

# DaScripts
alias DasIP='echo "$(curl -s http://ipecho.net/plain)"'
alias DasPing='sudo ping daspat.fr -c 15'
alias DasMount='sudo mount /dev/sdb1 /mnt/usb && cd /mnt/usb'
alias DaSuya='yaourt -Suya --noconfirm && sudo pacman-optimize'
alias DaSyu='yaourt -Syu --noconfirm && sudo pacman-optimize'
alias DasUmount='sudo umount /mnt/usb/'
alias DasV='uname -a'
alias refreshmirrors='sudo reflector --verbose -l 200 --sort rate --save /etc/pacman.d/mirrorlist'
alias vncserv='x0vncserver -display :0 -passwordfile ~/.vnc/passwd'

source $ZSH/oh-my-zsh.sh

# Browser
export BROWSER="firefox"

# Editor
export EDITOR="vim"

# PATH
export PATH="$PATH:/home/dasfranck/bin"

# Locale
export LC_NUMERIC="fr_FR.utf8"
export LC_MONETARY="fr_FR.utf8"
export LC_PAPER="fr_FR.utf8"
export LC_ADDRESS="fr_FR.utf8"
export LC_TELEPHONE="fr_FR.utf8"
export LC_MEASUREMENT="fr_FR.utf8"

# Acceleration Video Driver
export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=r600

# Colored man pages
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

# GPG-Agent as SSH-Agent
if ! pgrep -x -u "${USER}" gpg-agent >/dev/null 2>&1; then
  gpg-connect-agent /bye >/dev/null 2>&1
fi
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
fi
GPG_TTY=$(tty)
export GPG_TTY
gpg-connect-agent updatestartuptty /bye >/dev/null
